# Fonts///////////////////////////////////////
font_size        10.0

#Cursors//////////////////////////////////////
shell_integration no-cursor
cursor_shape beam
cursor_blink_interval     0.5

#window///////////////////////////////////////
background_opacity 0.85
background #1f1f1f

#setting idk abt//////////////////////////////
shell_integration enabled
comfirm_os_window_close -1
